# Generated by Django 5.1.4 on 2025-08-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_billing_area_user_billing_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='billing_area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_block',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_house',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_road',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_block',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_house',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_road',
        ),
    ]
