# Generated by Django 5.1.4 on 2025-08-31 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_billing_area_remove_user_billing_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read'), ('Pending', 'Pending')], default='Unread', max_length=20)),
                ('type', models.CharField(choices=[('Order Update', 'Order Update'), ('Promotional', 'Promotional'), ('Alert', 'Alert'), ('System', 'System')], default='System', max_length=50)),
            ],
        ),
    ]
