# Generated by Django 5.1.4 on 2025-08-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Order Update', 'Order Update'), ('Promotional', 'Promotional'), ('Alert', 'Alert'), ('System', 'System'), ('New Customer', 'New Customer')], default='System', max_length=50),
        ),
    ]
