# Generated by Django 5.2.5 on 2025-08-31 23:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, help_text='Select a parent category if this is a subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('tag', models.CharField(choices=[('featured', 'Featured'), ('on_sale', 'On Sale'), ('top_rated', 'Top Rated'), ('normal', 'Normal'), ('clearance', 'Clearance'), ('new_arrival', 'New Arrivals'), ('limited', 'Limited Quantities'), ('best_choice', 'The Best Choices')], default='normal', help_text='Product label for homepage filtering', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(help_text='Select category or subcategory', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.category')),
            ],
        ),
    ]
