# Generated by Django 5.2.5 on 2025-09-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('on_sale', 'On Sale'), ('top_rated', 'Top Rated'), ('normal', 'Normal'), ('new_arrival', 'New Arrival'), ('featured', 'Featured'), ('best_seller', 'Best Seller'), ('special_offer', 'Special offer'), ('banner', 'Banner')], default='normal', help_text='Product label for homepage filtering', max_length=30),
        ),
    ]
