# Generated by Django 5.2.5 on 2025-09-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_wishlist'),
        ('accounts', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
        migrations.AddField(
            model_name='wishlist',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='accounts.user'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('session_key', 'product'), ('user', 'product')},
        ),
    ]
