# Generated by Django 5.2.5 on 2025-09-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_wishlist_unique_together_wishlist_session_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('session_key', 'product')},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='session_key',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
    ]
